[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600
lib_deps =
    knolleary/PubSubClient
    bblanchon/ArduinoJson
    adafruit/DHT sensor library
    adafruit/Adafruit Unified Sensor
build_flags =
    -DCORE_DEBUG_LEVEL=0
    -O2
    -DCONFIG_ARDUINO_LOOP_STACK_SIZE=8192
    -Wall
    -Wextra