"""
export_weights.py
=================
Extracts weights from the trained Keras model and exports them
as a hardcoded C header file for ESP32 inference.

NO TFLite runtime needed on ESP32 — weights are baked in directly.

Run AFTER train_tflite.py:
    python export_weights.py
"""

import numpy as np
from pathlib import Path

BASE_DIR     = Path(__file__).parent
MODEL_DIR    = BASE_DIR / "models"
EDGE_SRC_DIR = BASE_DIR.parent / "edge_device" / "src"

FEATURE_COLS = [
    "duration", "src_bytes", "dst_bytes", "src_pkts", "dst_pkts",
    "packet_rate", "byte_rate", "bytes_per_pkt", "payload_ratio",
    "proto_tcp", "proto_udp", "proto_icmp",
    "conn_ok", "conn_s0", "conn_rej",
    "jitter", "flow_weight", "magnitude", "variance",
    "logged_in", "num_failed_logins", "srv_count",
]

def arr_to_c(arr, name, dtype="float"):
    flat = arr.flatten()
    vals = ", ".join(f"{v:.6f}f" for v in flat)
    shape = "x".join(str(d) for d in arr.shape)
    return f"// shape: {shape}\nconst {dtype} {name}[{len(flat)}] = {{\n  {vals}\n}};\n"

def main():
    import pandas as pd
    from sklearn.preprocessing import StandardScaler

    print("Loading data and retraining to extract weights...")

    # Load data
    normal = pd.read_csv(str(BASE_DIR / "dataset" / "data.csv"))
    normal = normal[FEATURE_COLS].copy()
    normal["label"] = 0

    attack = pd.read_csv(str(BASE_DIR / "dataset" / "realtime_esp32.csv"),
                         on_bad_lines="skip")
    attack = attack[attack["timestamp"] != "timestamp"]
    attack = attack[attack["edge_decision"] == "attack"]
    attack = attack[FEATURE_COLS].copy()
    attack["label"] = 1

    import pandas as pd2
    df = pd.concat([normal, attack], ignore_index=True).dropna()
    df[FEATURE_COLS] = df[FEATURE_COLS].apply(pd.to_numeric, errors="coerce").fillna(0)

    X = df[FEATURE_COLS].values.astype(np.float32)
    y = df["label"].values.astype(np.float32)

    # Scale
    scaler = StandardScaler()
    X_sc   = scaler.fit_transform(X).clip(-10, 10).astype(np.float32)

    print(f"  Samples: {len(X)}  Attack rate: {y.mean():.1%}")

    # Train
    import tensorflow as tf

    n_attack = int(y.sum())
    n_normal = int((1-y).sum())
    cw = {0: 1.0, 1: n_normal / max(n_attack, 1)}

    model = tf.keras.Sequential([
        tf.keras.layers.Input(shape=(22,)),
        tf.keras.layers.Dense(32, activation="relu"),
        tf.keras.layers.Dropout(0.2),
        tf.keras.layers.Dense(16, activation="relu"),
        tf.keras.layers.Dense(1,  activation="sigmoid"),
    ])
    model.compile(optimizer="adam", loss="binary_crossentropy", metrics=["accuracy"])
    model.fit(X_sc, y, epochs=50, batch_size=32,
              validation_split=0.2, class_weight=cw, verbose=1)

    loss, acc = model.evaluate(X_sc, y, verbose=0)
    print(f"\n  Accuracy: {acc:.4f}")

    # Extract weights
    # Layer 0 = Dense(32) — weights shape (22,32), bias shape (32,)
    # Layer 2 = Dense(16) — weights shape (32,16), bias shape (16,)
    # Layer 3 = Dense(1)  — weights shape (16,1),  bias shape (1,)
    dense_layers = [l for l in model.layers if isinstance(l, tf.keras.layers.Dense)]

    w1, b1 = dense_layers[0].get_weights()  # (22,32), (32,)
    w2, b2 = dense_layers[1].get_weights()  # (32,16), (16,)
    w3, b3 = dense_layers[2].get_weights()  # (16,1),  (1,)

    print(f"\n  w1: {w1.shape}  b1: {b1.shape}")
    print(f"  w2: {w2.shape}  b2: {b2.shape}")
    print(f"  w3: {w3.shape}  b3: {b3.shape}")

    # Export tinyml_weights.h
    EDGE_SRC_DIR.mkdir(parents=True, exist_ok=True)
    out_path = EDGE_SRC_DIR / "tinyml_weights.h"

    mean_str  = ", ".join(f"{v:.6f}f" for v in scaler.mean_)
    scale_str = ", ".join(f"{v:.6f}f" for v in scaler.scale_)

    content = f"""#pragma once
/*
  tinyml_weights.h
  Auto-generated by export_weights.py
  Architecture: 22 → Dense(32,relu) → Dense(16,relu) → Dense(1,sigmoid)
  Accuracy: {acc:.4f}
  Samples:  {len(X)} ({n_normal} normal + {n_attack} attack)
*/

#ifndef TINYML_WEIGHTS_H
#define TINYML_WEIGHTS_H

#define NN_INPUT_SIZE  22
#define NN_H1_SIZE     32
#define NN_H2_SIZE     16
#define NN_OUTPUT_SIZE  1
#define NN_THRESHOLD   0.5f

// ── Scaler ────────────────────────────────────────────────────
const float NN_MEAN[22]  = {{ {mean_str} }};
const float NN_SCALE[22] = {{ {scale_str} }};

// ── Layer 1: 22→32 ────────────────────────────────────────────
{arr_to_c(w1.T, "NN_W1")}
{arr_to_c(b1,   "NN_B1")}
// ── Layer 2: 32→16 ────────────────────────────────────────────
{arr_to_c(w2.T, "NN_W2")}
{arr_to_c(b2,   "NN_B2")}
// ── Layer 3: 16→1 ─────────────────────────────────────────────
{arr_to_c(w3.T, "NN_W3")}
{arr_to_c(b3,   "NN_B3")}

#endif // TINYML_WEIGHTS_H
"""

    out_path.write_text(content)
    print(f"\n  ✅ Exported: {out_path}")
    print(f"  File size : {out_path.stat().st_size / 1024:.1f} KB")

if __name__ == "__main__":
    main()